## 練習時間
在小量的資料上，我們用眼睛就可以看得出來程式碼是否有跑出我們理想中的結果

請嘗試想像一個你需要的資料結構 (裡面的值可以是隨機的)，然後用上述的方法把它變成 pandas DataFrame

#### Ex: 想像一個 dataframe 有兩個欄位，一個是國家，一個是人口，求人口數最多的國家

### Hints: [隨機產生數值](https://blog.csdn.net/christianashannon/article/details/78867204)

In [1]:
import pandas as pd
import numpy as np

In [2]:
country = ['Taiwan','Japan','Canada']
# population = np.random.randint(10,size = 3)*100000
population = np.random.randint(10**8, size= 3)
print(population)

[91661087 82628534 42920063]


In [6]:
data = {'國家': country ,
        '人口': population}
data = pd.DataFrame(data)
display(data)

國家        人口
0  Taiwan  91661087
1   Japan  82628534
2  Canada  42920063

In [4]:
population_max = max(population)
print(population_max)

91661087


In [7]:
# 顯示最大值
data.loc[data['人口'].idxmax()]

國家      Taiwan
人口    91661087
Name: 0, dtype: object

In [8]:
# test
np.random.rand(10)

array([0.632933  , 0.49381247, 0.75876229, 0.78071903, 0.57940782,
       0.90061049, 0.21843718, 0.70921452, 0.49744584, 0.83415213])

In [9]:
np.random.randn(10)

array([ 0.71545112, -1.53165981,  0.32700547,  1.28658316,  1.85185944,
        2.41426888, -0.94756627, -0.59374402,  1.25023982, -0.42089257])

In [10]:
np.random.randint(20,size = 10)

array([17, 14, 19,  3, 13,  8,  0,  0,  0,  3])